### ISSUE TITLE
Dependency on D3DX

### ISSUE THREAD

**Issue by CookiePLMonster** [xan1242/NFSMW_XenonEffects#1] opened 2023-02-21 11:40 UTC
The use of `d3dx9.lib` required by `D3DXCreateTextureFromFileInMemory` and `D3DXCreateTextureFromFile` creates a dependency on D3DX9 that is not shipped in Windows by default. This might lead to people complaining about the mod failing to load if they've not had to install the DX end user runtimes in the past, or if no retail/Steam game did. I don't know if NFS MW's installer does, but if it does then it's a version much older than what you're linking against (`d3dx9_43.dll`).

There are a few ways to solve this:
1. Require the user to install [DirectX End-User Runtimes](https://www.microsoft.com/download/details.aspx?id=35). This redist is big and outdated though, and requiring it just for one DLL is eh.
2. Ship an updated, resigned `d3dx9_43.dll` from a NuGet package described in [Legacy D3DX on NuGet](https://walbourn.github.io/legacy-d3dx-on-nuget/). This is the currently recommended way of using D3DX9 is you really, **really** need it.
3. Since `D3DXMATRIX` types do not introduce a dependency and only the texture loader functions do, you may replace these functions with `DDSTextureLoader9` from [DirectXTex](https://github.com/microsoft/DirectXTex). It's permissively licensed and modular, so essentially you could even just drag this one .cpp and .h file into the project and use it directly, removing the need to link against the DLL in the first place.

**Comment by xan1242** [comment] 2023-02-21 15:55
Yeah, I had this in mind.

So in code there's really only 2 real dependencies on D3DX: the texture loading and effect pass functions.

For texture loading, I could use your solution 3, however, my idea was to just use the game itself via its own texture loading functions (GetTextureInfo). It's partially in there, but the issue is that I just hadn't told SetTexture to use the loaded texture since it was simpler this way to get something going.

For effect pass functions, I guess it just comes down to vtable pointers, so I believe I should be able to either use the existing header somehow without linking it. Worst case, I'll just hack up my own solution in asm like I had a few builds ago, it's not too complex to do this.

As for D3DXMATRIX, I'll probably just replace it with my own (I called it bMatrix4 in the code).

**Comment by CookiePLMonster** [comment] 2023-02-21 15:58
You don't seem to be creating the `ID3DXEffect` yourself so you don't actually need the DLL for it. Using headers alone should be fine, it's specifically linking against the DLL that is problematic.

**Comment by xan1242** [comment] 2023-02-21 18:10
Fixed in https://github.com/xan1242/NFSMW_XenonEffects/commit/0b5fa20f6e0cab4e751c878fdeee74997ea8b74b

**Closed as completed by xan1242** 2023-02-21 18:10 UTC
